name = "DuckDB"
uuid = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
authors = ["Mark Raasveldt <mark@duckdblabs.com", "Hannes MÃ¼hleisen <hannes@duckdblabs.com>"]
version = "1.4.1"

[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DuckDB_jll = "2cbbab25-fc8b-58cf-88d4-687a02676033"
FixedPointDecimals = "fb4d412d-6eee-574d-9565-ede6634db7b0"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
WeakRefStrings = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"

[compat]
DBInterface = "2.5"
DuckDB_jll = "1.4.1"
FixedPointDecimals = "0.4, 0.5, 0.6"
Tables = "1.7"
WeakRefStrings = "1.4"
julia = "1.10"
