name = "DuckDB"
uuid = "dc41c802-e0d0-4f5a-8bba-22eb8b17d8a4"
authors = ["Mark Raasveldt <mark@duckdblabs.com", "Hannes MÃ¼hleisen <hannes@duckdblabs.com>"]
version = "0.3.2"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DuckDB_jll = "2cbbab25-fc8b-58cf-88d4-687a02676033"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
WeakRefStrings = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
