name: Close Stale Issues
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  close_stale_issues:
    permissions:
      actions: write
      contents: write # only for delete-branch option
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues
        uses: actions/stale@v9
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          stale-issue-message: 'This issue is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 30 days.'
          stale-pr-message: 'This pull request is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 30 days.'
          close-issue-message: 'This issue was closed because it has been stale for 30 days with no activity.'
          close-pr-message: 'This pull request was closed because it has been stale for 30 days with no activity.'
          exempt-issue-labels: 'no stale'
          exempt-pr-labels: 'no stale'
          days-before-stale: 365
          days-before-close: 30
          operations-per-run: 500
          stale-issue-label: stale
          stale-pr-label: stale
