# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - '**'
      - '!main'
      - '!feature'
    tags:
      - '**'
    paths-ignore:
      - '**.md'
      - 'examples/**'
      - 'test/**'
      - 'tools/**'
      - '!tools/swift/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/R_CMD_CHECK.yml'

  pull_request:
    types: [ opened, reopened, ready_for_review ]
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '!tools/odbc/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/R_CMD_CHECK.yml'


name: R-CMD-check

env:
  DUCKDB_R_REPO: 'duckdb/duckdb-r'
  TARGET_REF: 'main'
  DUCKDB_R_SRC: 'duckdb-r'
  DUCKDB_SRC: 'duckdb'
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: true
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.DUCKDB_SRC }}

      - uses: actions/checkout@v3
        with:
          repository: ${{ env.DUCKDB_R_REPO }}
          path: ${{ env.DUCKDB_R_SRC }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: ${{ env.DUCKDB_R_SRC }}
          extra-packages: any::rcmdcheck
          needs: check

      - name: Apply duckdb-r patches
        shell: bash
        working-directory: ${{ env.DUCKDB_R_SRC }}
        run: |
          shopt -s nullglob
          for filename in $GITHUB_WORKSPACE/$DUCKDB_SRC/.github/patches/duckdb-r/*.patch; do
            git apply $filename
          done

      # needed so we can run git commit in vendor.sh
      - name: setup github and create parallel builds
        shell: bash
        run: |
          git config --global user.email "duck@duck.com"
          git config --global user.name "mr. duck"
          mkdir -p ~/.R
          echo 'MAKEFLAGS = -j2' >> ~/.R/Makevars

      # error is from git_dev_version() but does not affect this workflow
      - name: update duckdb-r src code with PR code
        shell: bash
        working-directory: ${{ env.DUCKDB_R_SRC }}
        run: ./vendor.sh $GITHUB_WORKSPACE/$DUCKDB_SRC

      - uses: r-lib/actions/check-r-package@v2
        with:
          # Fails on R 3.6 on Windows, remove when this job is removed?
          args: 'c("--no-tests", "--no-manual", "--as-cran", "--no-multiarch")'
          working-directory: ${{ env.DUCKDB_R_SRC }}
